FROM centos:7

# replace repos to avoid the mirror URL problem
ADD centos/repos /etc/yum.repos.d

# Install EPEL and required packages
RUN yum -y install epel-release && \
    yum -y groupinstall "X Window System" "Xfce" && \
    yum -y install \
    xrdp \
    supervisor \
    xorg-x11-server-Xorg \
    xorg-x11-fonts-* \
    xorg-x11-utils \
    xorg-x11-xinit \
    xfwm4 \
    xfdesktop \
    thunar \
    dbus \
    dbus-x11 \
    && yum clean all

# Create user
RUN useradd -m -s /bin/bash coder && \
    echo "coder:coder" | chpasswd && \
    usermod -aG wheel coder && \
    echo "coder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Configure XRDP
RUN mkdir -p /etc/xrdp && \
    echo "[Globals]" > /etc/xrdp/xrdp.ini && \
    echo "ini_version=1" >> /etc/xrdp/xrdp.ini && \
    echo "fork=true" >> /etc/xrdp/xrdp.ini && \
    echo "port=3389" >> /etc/xrdp/xrdp.ini && \
    echo "use_vsock=false" >> /etc/xrdp/xrdp.ini && \
    echo "security_layer=rdp" >> /etc/xrdp/xrdp.ini && \
    echo "crypt_level=none" >> /etc/xrdp/xrdp.ini && \
    echo "certificate=" >> /etc/xrdp/xrdp.ini && \
    echo "key_file=" >> /etc/xrdp/xrdp.ini && \
    echo "ssl_protocols=TLSv1, TLSv1.1, TLSv1.2" >> /etc/xrdp/xrdp.ini && \
    echo "channel_code=1" >> /etc/xrdp/xrdp.ini && \
    echo "max_bpp=24" >> /etc/xrdp/xrdp.ini && \
    echo "bitmap_compression=false" >> /etc/xrdp/xrdp.ini && \
    echo "" >> /etc/xrdp/xrdp.ini && \
    echo "[Xorg]" >> /etc/xrdp/xrdp.ini && \
    echo "name=Xorg" >> /etc/xrdp/xrdp.ini && \
    echo "lib=libxup.so" >> /etc/xrdp/xrdp.ini && \
    echo "username=ask" >> /etc/xrdp/xrdp.ini && \
    echo "password=ask" >> /etc/xrdp/xrdp.ini && \
    echo "ip=127.0.0.1" >> /etc/xrdp/xrdp.ini && \
    echo "port=-1" >> /etc/xrdp/xrdp.ini

# Configure sesman.ini
RUN echo "[Globals]" > /etc/xrdp/sesman.ini && \
    echo "ListenAddress=127.0.0.1" >> /etc/xrdp/sesman.ini && \
    echo "ListenPort=3350" >> /etc/xrdp/sesman.ini && \
    echo "EnableUserWindowManager=true" >> /etc/xrdp/sesman.ini && \
    echo "UserWindowManager=startwm.sh" >> /etc/xrdp/sesman.ini && \
    echo "DefaultWindowManager=startwm.sh" >> /etc/xrdp/sesman.ini && \
    echo "" >> /etc/xrdp/sesman.ini && \
    echo "[Security]" >> /etc/xrdp/sesman.ini && \
    echo "AllowRootLogin=true" >> /etc/xrdp/sesman.ini && \
    echo "MaxLoginRetry=4" >> /etc/xrdp/sesman.ini && \
    echo "" >> /etc/xrdp/sesman.ini && \
    echo "[Sessions]" >> /etc/xrdp/sesman.ini && \
    echo "X11DisplayOffset=10" >> /etc/xrdp/sesman.ini && \
    echo "MaxSessions=50" >> /etc/xrdp/sesman.ini && \
    echo "KillDisconnected=false" >> /etc/xrdp/sesman.ini && \
    echo "DisconnectedTimeLimit=0" >> /etc/xrdp/sesman.ini && \
    echo "IdleTimeLimit=0" >> /etc/xrdp/sesman.ini

# Configure X server
RUN echo "allowed_users=anybody" > /etc/X11/Xwrapper.config && \
    echo "needs_root_rights=yes" >> /etc/X11/Xwrapper.config && \
    mkdir -p /etc/X11/xrdp && \
    echo 'Section "ServerFlags"' > /etc/X11/xrdp/xorg.conf && \
    echo '    Option "DontVTSwitch" "true"' >> /etc/X11/xrdp/xorg.conf && \
    echo '    Option "AutoAddDevices" "true"' >> /etc/X11/xrdp/xorg.conf && \
    echo '    Option "AutoEnableDevices" "true"' >> /etc/X11/xrdp/xorg.conf && \
    echo 'EndSection' >> /etc/X11/xrdp/xorg.conf && \
    echo 'Section "Module"' >> /etc/X11/xrdp/xorg.conf && \
    echo '    Load "glx"' >> /etc/X11/xrdp/xorg.conf && \
    echo 'EndSection' >> /etc/X11/xrdp/xorg.conf

# Create startup script
RUN echo '#!/bin/bash' > /etc/xrdp/startwm.sh && \
    echo 'export LANG=en_US.UTF-8' >> /etc/xrdp/startwm.sh && \
    echo 'export DISPLAY=:10' >> /etc/xrdp/startwm.sh && \
    echo 'export XRDP_SESSION=1' >> /etc/xrdp/startwm.sh && \
    echo 'export XDG_SESSION_TYPE=x11' >> /etc/xrdp/startwm.sh && \
    echo 'export XDG_RUNTIME_DIR=/run/user/$(id -u)' >> /etc/xrdp/startwm.sh && \
    echo 'export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket' >> /etc/xrdp/startwm.sh && \
    echo 'mkdir -p $XDG_RUNTIME_DIR' >> /etc/xrdp/startwm.sh && \
    echo 'chmod 700 $XDG_RUNTIME_DIR' >> /etc/xrdp/startwm.sh && \
    echo 'chown $(id -u):$(id -g) $XDG_RUNTIME_DIR' >> /etc/xrdp/startwm.sh && \
    echo 'exec startxfce4' >> /etc/xrdp/startwm.sh && \
    chmod +x /etc/xrdp/startwm.sh

# Configure supervisord
RUN echo "[supervisord]" > /etc/supervisord.conf && \
    echo "nodaemon=true" >> /etc/supervisord.conf && \
    echo "user=root" >> /etc/supervisord.conf && \
    echo "" >> /etc/supervisord.conf && \
    echo "[program:dbus]" >> /etc/supervisord.conf && \
    echo "command=/usr/bin/dbus-daemon --system --nofork" >> /etc/supervisord.conf && \
    echo "user=root" >> /etc/supervisord.conf && \
    echo "autorestart=true" >> /etc/supervisord.conf && \
    echo "" >> /etc/supervisord.conf && \
    echo "[program:xrdp-sesman]" >> /etc/supervisord.conf && \
    echo "command=/usr/sbin/xrdp-sesman --nodaemon" >> /etc/supervisord.conf && \
    echo "user=root" >> /etc/supervisord.conf && \
    echo "autorestart=true" >> /etc/supervisord.conf && \
    echo "" >> /etc/supervisord.conf && \
    echo "[program:xrdp]" >> /etc/supervisord.conf && \
    echo "command=/usr/sbin/xrdp --nodaemon" >> /etc/supervisord.conf && \
    echo "user=root" >> /etc/supervisord.conf && \
    echo "autorestart=true" >> /etc/supervisord.conf

# Set up required directories and permissions
RUN mkdir -p /tmp/.X11-unix && \
    chmod 1777 /tmp/.X11-unix && \
    mkdir -p /run/dbus && \
    mkdir -p /var/run/dbus && \
    mkdir -p /var/log/xrdp && \
    chown -R coder:coder /home/coder

# Set environment variables
ENV DISPLAY=:10
ENV LANG=en_US.UTF-8
ENV DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket

# Expose XRDP port
EXPOSE 3389

# Start supervisord
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
