FROM centos:7

# replace repos to avoid the mirror URL problem
ADD centos/repos /etc/yum.repos.d

# Install base dependencies
RUN yum install -y epel-release && \
    yum update -y && \
    yum install -y \
    wget \
    tar \
    gzip \
    make \
    gcc \
    gcc-c++ \
    bzip2 \
    git \
    file \
    vim \
    net-tools \
    which \
    zlib-devel \
    glibc-devel \
    glibc-devel.i686 \
    glibc-i686 \
    libmpc-devel \
    mpfr-devel \
    gmp-devel

# Install Development Tools group
RUN yum groupinstall -y "Development Tools"

# Build and install make 4.3
WORKDIR /tmp
RUN wget https://ftp.gnu.org/gnu/make/make-4.3.tar.gz && \
    tar xzf make-4.3.tar.gz && \
    cd make-4.3 && \
    ./configure --prefix=/usr && \
    make -j$(nproc) && \
    make install && \
    cd /tmp && \
    rm -rf make-4.3*

# Install GCC 9
WORKDIR /tmp
RUN wget https://ftp.gnu.org/gnu/gcc/gcc-9.5.0/gcc-9.5.0.tar.gz && \
    tar xf gcc-9.5.0.tar.gz && \
    cd gcc-9.5.0 && \
    ./configure \
        --enable-languages=c,c++ \
        --disable-multilib \
        --with-system-zlib \
        --prefix=/usr && \
    make -j$(nproc) && \
    make install && \
    cd /tmp && \
    rm -rf gcc-9.5.0*

# Update path to use new gcc
ENV PATH=/usr/local/bin:$PATH

RUN echo "Checking environment after GCC build: $LD_LIBRARY_PATH"

RUN echo "Make version: $(make --version | head -1)"

RUN echo "GCC version: $(gcc --version | head -1)"

# Build and install glibc 2.28
WORKDIR /tmp
RUN wget https://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz

# Verify toolchain versions
RUN gcc --version && make --version && ldd --version
