name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Ubuntu version (latest)
      - name: Build and push Ubuntu Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cursord:latest
          cache-from: type=gha,scope=ubuntu
          cache-to: type=gha,mode=max,scope=ubuntu

      # Build and push Ubuntu version
      - name: Build and push Ubuntu Docker with Desktop image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ubuntu
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/AIEditor:ubuntu
          cache-from: type=gha,scope=ubuntu-desktop
          cache-to: type=gha,mode=max,scope=ubuntu-desktop

      # Build and push CentOS toolchain base
      - name: Build and push CentOS toolchain base
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.centos-base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/centos7-base:latest
          cache-from: type=gha,scope=centos-base
          cache-to: type=gha,mode=max,scope=centos-base

      # Build and push CentOS cursor version
      - name: Build and push CentOS cursor image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.centos
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cursord:centos
          cache-from: type=gha,scope=centos-desktop
          cache-to: type=gha,mode=max,scope=centos-desktop
