name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore Docker build cache
        uses: actions/cache/restore@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Echo build start
        run: echo "Starting Docker build process..."

      # Build Ubuntu version (latest)
      - name: Build Ubuntu Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cursord:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          load: true

      # Build CentOS toolchain base
      - name: Build CentOS toolchain base
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.centos-base
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/centos7-base:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          load: true

      # Build CentOS cursor version
      - name: Build CentOS cursor image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.centos
          push: false
          build-args: |
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cursord:centos
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          load: true

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Save Docker build cache
        uses: actions/cache/save@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Test images
        run: |
          echo "Testing if images were built successfully..."
          docker images | grep "${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Image details above"

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: github.event_name != 'pull_request'
        run: |
          echo "Starting push to Docker Hub..."
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cursord:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/centos7-base:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cursord:centos
          echo "Push completed"
