name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Echo build start
        run: echo "Starting Docker build process..."

      # Build Ubuntu version (latest)
      - name: Build Ubuntu Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cursord:latest
          cache-from: type=gha,scope=ubuntu
          cache-to: type=gha,mode=max,scope=ubuntu
          load: true

      # Build CentOS toolchain base
      - name: Build CentOS toolchain base
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.centos-base
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/centos7-base:latest
          cache-from: type=gha,scope=centos-base
          cache-to: type=gha,mode=max,scope=centos-base
          load: true

      # Build CentOS cursor version
      - name: Build CentOS cursor image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.centos
          push: false
          build-args: |
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cursord:centos
          cache-from: type=gha,scope=centos
          cache-to: type=gha,mode=max,scope=centos
          load: true

      - name: Test images
        run: |
          echo "Testing if images were built successfully..."
          docker images | grep "${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Image details above"

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: github.event_name != 'pull_request'
        run: |
          echo "Starting push to Docker Hub..."
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cursord:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/centos7-base:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cursord:centos
          echo "Push completed"
